name: Run Browser Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.1

      - name: Cache Deno dependencies
        uses: runs-on/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}

      - name: Setup required tooling for Browser Tests
        run: deno task test:browser:setup

      - name: Run Unit Tests
        run: deno task test:unit

      - name: Run Browser Tests
        run: deno task test:browser:all
        env:
          VOI__VERBOSE: true
          VOI__LOG_STDIO: true

      - name: Run Browser Tests (no-js)
        run: deno task test:browser:all:no-js
        env:
          VOI__JS_DISABLED_IN_TESTS: true
          VOI__VERBOSE: true
          VOI__LOG_STDIO: true
