name: Typecheck & Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.1

      - name: Cache Deno dependencies
        uses: runs-on/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}

      - name: Run Type Check
        run: deno check

      - name: Run Lint
        run: deno lint

      - name: Run Format check
        run: deno fmt --check
